/*******************************************************************************
 **+--------------------------------------------------------------------------+**
 **|                            ****                                          |**
 **|                            ****                                          |**
 **|                            ******o***                                    |**
 **|                      ********_///_****                                   |**
 **|                      ***** /_//_/ ****                                   |**
 **|                       ** ** (__/ ****                                    |**
 **|                           *********                                      |**
 **|                            ****                                          |**
 **|                            ***                                           |**
 **|                                                                          |**
 **|         Copyright (c) 2016 Texas Instruments Incorporated                |**
 **|                        ALL RIGHTS RESERVED                               |**
 **|                                                                          |**
 **| Permission to use, copy, modify, or distribute this software,            |**
 **| whether in part or in whole, for any purpose is forbidden without        |**
 **| a signed licensing agreement and NDA from Texas Instruments              |**
 **| Incorporated (TI).                                                       |**
 **|                                                                          |**
 **| TI makes no representation or warranties with respect to the             |**
 **| performance of this computer program, and specifically disclaims         |**
 **| any responsibility for any damages, special or consequential,            |**
 **| connected with the use of this program.                                  |**
 **|                                                                          |**
 **+--------------------------------------------------------------------------+**
 *******************************************************************************/


/******************************************************************************
 *                                                                             *
 * module name       :MMALIB                                                   *
 *                                                                             *
 * module descripton :Matrix Multiply Accelerator Library module for C7x+MMA   *
 *                                                                             *
 * Copyright (C) 2017-2018 Texas Instruments Incorporated - http://www.ti.com/ *
 * ALL RIGHTS RESERVED                                                         *
 *                                                                             *
 ******************************************************************************/

/*This file is autogenerated*/
/*Please do not edit*/

#include "MMALIB_CNN_convolve_row_ixX_ixX_oxX_idat.h"

#define TEST_CASE 281

#if ((TEST_CASE == 13) || (TEST_CATEGORY == 1000))
#include "test_data/MMALIB_CNN_convolve_row_ixX_ixX_oxX_idat_testcase13.h"
#endif

#if ((TEST_CASE == 72) || (TEST_CATEGORY == 1000))
#include "test_data/MMALIB_CNN_convolve_row_ixX_ixX_oxX_idat_testcase72.h"
#endif

#if ((TEST_CASE == 78) || (TEST_CATEGORY == 1000))
#include "test_data/MMALIB_CNN_convolve_row_ixX_ixX_oxX_idat_testcase78.h"
#endif

#if ((TEST_CASE == 104) || (TEST_CATEGORY == 1000))
#include "test_data/MMALIB_CNN_convolve_row_ixX_ixX_oxX_idat_testcase104.h"
#endif

#if ((TEST_CASE == 123) || (TEST_CATEGORY == 1000))
#include "test_data/MMALIB_CNN_convolve_row_ixX_ixX_oxX_idat_testcase123.h"
#endif

#if ((TEST_CASE == 205) || (TEST_CATEGORY == 1000))
#include "test_data/MMALIB_CNN_convolve_row_ixX_ixX_oxX_idat_testcase205.h"
#endif

#if ((TEST_CASE == 227) || (TEST_CATEGORY == 1000))
#include "test_data/MMALIB_CNN_convolve_row_ixX_ixX_oxX_idat_testcase227.h"
#endif

#if ((TEST_CASE == 281) || (TEST_CATEGORY == 1000))
#include "test_data/MMALIB_CNN_convolve_row_ixX_ixX_oxX_idat_testcase281.h"
#endif

/* #if (defined(ALL_TEST_CASES) || (TEST_CATEGORY == 200) || (EXTENDED_TEST_CASE == 500))
#include "test_data/extended_test_cases/MMALIB_CNN_convolve_row_ixX_ixX_oxX_idat_testcase500.h"
#endif */

//#if (defined(ALL_TEST_CASES) || (TEST_CATEGORY == 200) || (TEST_CATEGORY ==  100) || (EXTENDED_TEST_CASE == 519))

static convolve_row_ixX_ixX_oxX_testParams_t testParams[] =
{

#if ((TEST_CASE == 13) || (TEST_CATEGORY == 1000))
   {
      STATIC,                   //testPattern
      staticRefIn_case13,      
      staticRefKernel_case13,  
      staticRefOutput_case13,  
      3,                        //kernelWidth
      3,                        //kernelHeight
      1,                        //strideWidth
      1,                        //strideHeight
      1,                        //dilationHeight
      1,                        //dilationWidth
      256,                      //inWidth
      1,                        //pad
      256,                      //maxHeight
      1088,                     //inChoffset
      772,                      //validColsIn
      2304,                     //kDim
      2624,                     //pitchA
      64,                       //numOfOutputChKerBuf
      576,                      //pitchC 
      64,                       //subMChannels     
      256,                      //numInChannels    
      64,                       //numOutChannels   
      14,                       //qShift           
      20,                       //biasB     
      MMALIB_SUCCESS, //expectedStatusCode            
      MMALIB_RELU,              //activationType   
      MMALIB_INT8,              //dataTypeA        
      MMALIB_INT8,              //dataTypeB        
      MMALIB_UINT8,             //dataTypeC        
      MMALIB_LINEAR,            //mode             
      0,                        //circularOffset
      64,                       //totalN
      64,                       //subN
      0,                        //validColsPerRowIn
      0,                        //validRowsIn
      0,                        //outputPitchPerRow
      0,                        //inputPitchPerRow
      772,                      //validColsInlast
      0,                        //validColsPerRowInlast
      0,                        //validRowsInlast
      1,                        //numGroupsPerKernel
      MMALIB_TEST_OUTPUT_MSMC,  //outputDataLocation
      13,                       //testID
   },
#endif

#if ((TEST_CASE == 28) || (TEST_CATEGORY == 1000))
   {
      RANDOM,                   //testPattern
      NULL, NULL, NULL,        
      3,                        //kernelWidth
      3,                        //kernelHeight
      1,                        //strideWidth
      1,                        //strideHeight
      1,                        //dilationHeight
      1,                        //dilationWidth
      128,                      //inWidth
      1,                        //pad
      128,                      //maxHeight
      1024,                     //inChoffset
      388,                      //validColsIn
      1152,                     //kDim
      2304,                     //pitchA
      32,                       //numOfOutputChKerBuf
      256,                      //pitchC 
      32,                       //subMChannels     
      128,                      //numInChannels    
      32,                       //numOutChannels   
      24,                       //qShift           
      20,                       //biasB     
      MMALIB_SUCCESS, //expectedStatusCode            
      MMALIB_RELU,              //activationType   
      MMALIB_INT16,             //dataTypeA        
      MMALIB_INT16,             //dataTypeB        
      MMALIB_INT16,             //dataTypeC        
      MMALIB_SE_CIRCULAR,       //mode             
      0,                        //circularOffset
      384,                      //totalN
      128,                      //subN
      0,                        //validColsPerRowIn
      0,                        //validRowsIn
      0,                        //outputPitchPerRow
      0,                        //inputPitchPerRow
      388,                      //validColsInlast
      0,                        //validColsPerRowInlast
      0,                        //validRowsInlast
      1,                        //numGroupsPerKernel
      MMALIB_TEST_OUTPUT_MSMC,  //outputDataLocation
      28,                       //testID
   },
#endif

#if ((TEST_CASE == 72) || (TEST_CATEGORY == 1000))
   {
      STATIC,                   //testPattern
      staticRefIn_case72,      
      staticRefKernel_case72,  
      staticRefOutput_case72,  
      3,                        //kernelWidth
      3,                        //kernelHeight
      2,                        //strideWidth
      2,                        //strideHeight
      1,                        //dilationHeight
      1,                        //dilationWidth
      254,                      //inWidth
      1,                        //pad
      128,                      //maxHeight
      2048,                     //inChoffset
      1280,                     //validColsIn
      608,                      //kDim
      1216,                     //pitchA
      32,                       //numOfOutputChKerBuf
      512,                      //pitchC 
      32,                       //subMChannels     
      64,                       //numInChannels    
      32,                       //numOutChannels   
      24,                       //qShift           
      20,                       //biasB     
      MMALIB_SUCCESS, //expectedStatusCode            
      MMALIB_RELU,              //activationType   
      MMALIB_INT16,             //dataTypeA        
      MMALIB_INT16,             //dataTypeB        
      MMALIB_INT16,             //dataTypeC        
      MMALIB_SE_CIRCULAR,       //mode             
      0,                        //circularOffset
      32,                       //totalN
      32,                       //subN
      255,                      //validColsPerRowIn
      5,                        //validRowsIn
      256,                      //outputPitchPerRow
      512,                      //inputPitchPerRow
      1280,                     //validColsInlast
      255,                      //validColsPerRowInlast
      5,                        //validRowsInlast
      1,                        //numGroupsPerKernel
      MMALIB_TEST_OUTPUT_MSMC,  //outputDataLocation
      72,                       //testID
   },
#endif

#if ((TEST_CASE == 78) || (TEST_CATEGORY == 1000))
   {
      STATIC,                   //testPattern
      staticRefIn_case78,      
      staticRefKernel_case78,  
      staticRefOutput_case78,  
      5,                        //kernelWidth
      5,                        //kernelHeight
      2,                        //strideWidth
      2,                        //strideHeight
      1,                        //dilationHeight
      1,                        //dilationWidth
      252,                      //inWidth
      2,                        //pad
      21,                       //maxHeight
      4096,                     //inChoffset
      2816,                     //validColsIn
      1664,                     //kDim
      1664,                     //pitchA
      64,                       //numOfOutputChKerBuf
      512,                      //pitchC 
      64,                       //subMChannels     
      64,                       //numInChannels    
      64,                       //numOutChannels   
      10,                       //qShift           
      20,                       //biasB     
      MMALIB_SUCCESS, //expectedStatusCode            
      MMALIB_RELU,              //activationType   
      MMALIB_INT8,              //dataTypeA        
      MMALIB_UINT8,             //dataTypeB        
      MMALIB_UINT8,             //dataTypeC        
      MMALIB_SE_CIRCULAR,       //mode             
      0,                        //circularOffset
      64,                       //totalN
      64,                       //subN
      254,                      //validColsPerRowIn
      11,                       //validRowsIn
      128,                      //outputPitchPerRow
      256,                      //inputPitchPerRow
      2816,                     //validColsInlast
      254,                      //validColsPerRowInlast
      11,                       //validRowsInlast
      1,                        //numGroupsPerKernel
      MMALIB_TEST_OUTPUT_MSMC,  //outputDataLocation
      78,                       //testID
   },
#endif

#if ((TEST_CASE == 84) || (TEST_CATEGORY == 1000))
   {
      RANDOM,                   //testPattern
      NULL, NULL, NULL,        
      5,                        //kernelWidth
      5,                        //kernelHeight
      2,                        //strideWidth
      2,                        //strideHeight
      1,                        //dilationHeight
      1,                        //dilationWidth
      56,                       //inWidth
      2,                        //pad
      21,                       //maxHeight
      1024,                     //inChoffset
      640,                      //validColsIn
      832,                      //kDim
      1664,                     //pitchA
      64,                       //numOfOutputChKerBuf
      192,                      //pitchC 
      32,                       //subMChannels     
      32,                       //numInChannels    
      64,                       //numOutChannels   
      24,                       //qShift           
      20,                       //biasB     
      MMALIB_SUCCESS, //expectedStatusCode            
      MMALIB_RELU,              //activationType   
      MMALIB_INT16,             //dataTypeA        
      MMALIB_INT16,             //dataTypeB        
      MMALIB_INT16,             //dataTypeC        
      MMALIB_SE_CIRCULAR,       //mode             
      0,                        //circularOffset
      32,                       //totalN
      32,                       //subN
      58,                       //validColsPerRowIn
      10,                       //validRowsIn
      64,                       //outputPitchPerRow
      128,                      //inputPitchPerRow
      640,                      //validColsInlast
      58,                       //validColsPerRowInlast
      10,                       //validRowsInlast
      1,                        //numGroupsPerKernel
      MMALIB_TEST_OUTPUT_MSMC,  //outputDataLocation
      84,                       //testID
   },
#endif

#if ((TEST_CASE == 104) || (TEST_CATEGORY == 1000))
   {
      STATIC,                   //testPattern
      staticRefIn_case104,     
      staticRefKernel_case104, 
      staticRefOutput_case104, 
      7,                        //kernelWidth
      7,                        //kernelHeight
      2,                        //strideWidth
      2,                        //strideHeight
      1,                        //dilationHeight
      1,                        //dilationWidth
      252,                      //inWidth
      3,                        //pad
      128,                      //maxHeight
      4096,                     //inChoffset
      2816,                     //validColsIn
      800,                      //kDim
      1664,                     //pitchA
      32,                       //numOfOutputChKerBuf
      768,                      //pitchC 
      32,                       //subMChannels     
      16,                       //numInChannels    
      32,                       //numOutChannels   
      24,                       //qShift           
      20,                       //biasB     
      MMALIB_SUCCESS, //expectedStatusCode            
      MMALIB_RELU,              //activationType   
      MMALIB_INT16,             //dataTypeA        
      MMALIB_INT16,             //dataTypeB        
      MMALIB_INT16,             //dataTypeC        
      MMALIB_SE_CIRCULAR,       //mode             
      0,                        //circularOffset
      32,                       //totalN
      32,                       //subN
      255,                      //validColsPerRowIn
      11,                       //validRowsIn
      256,                      //outputPitchPerRow
      512,                      //inputPitchPerRow
      2816,                     //validColsInlast
      255,                      //validColsPerRowInlast
      11,                       //validRowsInlast
      1,                        //numGroupsPerKernel
      MMALIB_TEST_OUTPUT_MSMC,  //outputDataLocation
      104,                      //testID
   },
#endif

#if ((TEST_CASE == 123) || (TEST_CATEGORY == 1000))
   {
      STATIC,                   //testPattern
      staticRefIn_case123,     
      staticRefKernel_case123, 
      staticRefOutput_case123, 
      7,                        //kernelWidth
      7,                        //kernelHeight
      2,                        //strideWidth
      2,                        //strideHeight
      1,                        //dilationHeight
      1,                        //dilationWidth
      112,                      //inWidth
      3,                        //pad
      24,                       //maxHeight
      4096,                     //inChoffset
      3072,                     //validColsIn
      1600,                     //kDim
      1600,                     //pitchA
      64,                       //numOfOutputChKerBuf
      576,                      //pitchC 
      64,                       //subMChannels     
      32,                       //numInChannels    
      64,                       //numOutChannels   
      12,                       //qShift           
      20,                       //biasB     
      MMALIB_SUCCESS, //expectedStatusCode            
      MMALIB_RELU,              //activationType   
      MMALIB_INT8,              //dataTypeA        
      MMALIB_INT8,              //dataTypeB        
      MMALIB_INT8,              //dataTypeC        
      MMALIB_SE_CIRCULAR,       //mode             
      0,                        //circularOffset
      64,                       //totalN
      64,                       //subN
      115,                      //validColsPerRowIn
      24,                       //validRowsIn
      64,                       //outputPitchPerRow
      128,                      //inputPitchPerRow
      3072,                     //validColsInlast
      115,                      //validColsPerRowInlast
      24,                       //validRowsInlast
      1,                        //numGroupsPerKernel
      MMALIB_TEST_OUTPUT_MSMC,  //outputDataLocation
      123,                      //testID
   },
#endif

#if ((TEST_CASE == 190) || (TEST_CATEGORY == 1000))
   {
      RANDOM,                   //testPattern
      NULL, NULL, NULL,        
      5,                        //kernelWidth
      5,                        //kernelHeight
      1,                        //strideWidth
      1,                        //strideHeight
      1,                        //dilationHeight
      1,                        //dilationWidth
      64,                       //inWidth
      2,                        //pad
      16,                       //maxHeight
      4096,                     //inChoffset
      1036,                     //validColsIn
      1664,                     //kDim
      1664,                     //pitchA
      64,                       //numOfOutputChKerBuf
      832,                      //pitchC 
      64,                       //subMChannels     
      64,                       //numInChannels    
      64,                       //numOutChannels   
      12,                       //qShift           
      20,                       //biasB     
      MMALIB_SUCCESS, //expectedStatusCode            
      MMALIB_SATURATION,        //activationType   
      MMALIB_INT8,              //dataTypeA        
      MMALIB_INT8,              //dataTypeB        
      MMALIB_INT8,              //dataTypeC        
      MMALIB_SE_CIRCULAR,       //mode             
      0,                        //circularOffset
      64,                       //totalN
      64,                       //subN
      0,                        //validColsPerRowIn
      0,                        //validRowsIn
      0,                        //outputPitchPerRow
      0,                        //inputPitchPerRow
      1036,                     //validColsInlast
      0,                        //validColsPerRowInlast
      0,                        //validRowsInlast
      1,                        //numGroupsPerKernel
      MMALIB_TEST_OUTPUT_MSMC,  //outputDataLocation
      190,                      //testID
   },
#endif

#if ((TEST_CASE == 192) || (TEST_CATEGORY == 1000))
   {
      RANDOM,                   //testPattern
      NULL, NULL, NULL,        
      7,                        //kernelWidth
      7,                        //kernelHeight
      1,                        //strideWidth
      1,                        //strideHeight
      1,                        //dilationHeight
      1,                        //dilationWidth
      128,                      //inWidth
      3,                        //pad
      16,                       //maxHeight
      4096,                     //inChoffset
      1176,                     //validColsIn
      1600,                     //kDim
      1600,                     //pitchA
      64,                       //numOfOutputChKerBuf
      832,                      //pitchC 
      64,                       //subMChannels     
      32,                       //numInChannels    
      64,                       //numOutChannels   
      12,                       //qShift           
      20,                       //biasB     
      MMALIB_SUCCESS, //expectedStatusCode            
      MMALIB_SATURATION,        //activationType   
      MMALIB_INT8,              //dataTypeA        
      MMALIB_INT8,              //dataTypeB        
      MMALIB_INT8,              //dataTypeC        
      MMALIB_SE_CIRCULAR,       //mode             
      0,                        //circularOffset
      64,                       //totalN
      64,                       //subN
      0,                        //validColsPerRowIn
      0,                        //validRowsIn
      0,                        //outputPitchPerRow
      0,                        //inputPitchPerRow
      1176,                     //validColsInlast
      0,                        //validColsPerRowInlast
      0,                        //validRowsInlast
      1,                        //numGroupsPerKernel
      MMALIB_TEST_OUTPUT_MSMC,  //outputDataLocation
      192,                      //testID
   },
#endif

#if ((TEST_CASE == 199) || (TEST_CATEGORY == 1000))
   {
      RANDOM,                   //testPattern
      NULL, NULL, NULL,        
      1,                        //kernelWidth
      1,                        //kernelHeight
      1,                        //strideWidth
      1,                        //strideHeight
      1,                        //dilationHeight
      1,                        //dilationWidth
      64,                       //inWidth
      0,                        //pad
      32,                       //maxHeight
      2080,                     //inChoffset
      1024,                     //validColsIn
      96,                       //kDim
      576,                      //pitchA
      32,                       //numOfOutputChKerBuf
      2112,                     //pitchC 
      32,                       //subMChannels     
      64,                       //numInChannels    
      32,                       //numOutChannels   
      18,                       //qShift           
      20,                       //biasB     
      MMALIB_SUCCESS, //expectedStatusCode            
      MMALIB_RELU,              //activationType   
      MMALIB_INT16,             //dataTypeA        
      MMALIB_UINT16,            //dataTypeB        
      MMALIB_UINT16,            //dataTypeC        
      MMALIB_LINEAR,            //mode             
      0,                        //circularOffset
      32,                       //totalN
      32,                       //subN
      0,                        //validColsPerRowIn
      0,                        //validRowsIn
      0,                        //outputPitchPerRow
      0,                        //inputPitchPerRow
      1024,                     //validColsInlast
      0,                        //validColsPerRowInlast
      0,                        //validRowsInlast
      1,                        //numGroupsPerKernel
      MMALIB_TEST_OUTPUT_MSMC,  //outputDataLocation
      199,                      //testID
   },
#endif

#if ((TEST_CASE == 205) || (TEST_CATEGORY == 1000))
   {
      STATIC,                   //testPattern
      staticRefIn_case205,     
      staticRefKernel_case205, 
      staticRefOutput_case205, 
      1,                        //kernelWidth
      1,                        //kernelHeight
      1,                        //strideWidth
      1,                        //strideHeight
      1,                        //dilationHeight
      1,                        //dilationWidth
      256,                      //inWidth
      0,                        //pad
      32,                       //maxHeight
      8256,                     //inChoffset
      8192,                     //validColsIn
      64,                       //kDim
      576,                      //pitchA
      64,                       //numOfOutputChKerBuf
      8256,                     //pitchC 
      64,                       //subMChannels     
      32,                       //numInChannels    
      64,                       //numOutChannels   
      10,                       //qShift           
      20,                       //biasB     
      MMALIB_SUCCESS, //expectedStatusCode            
      MMALIB_RELU,              //activationType   
      MMALIB_INT8,              //dataTypeA        
      MMALIB_UINT8,             //dataTypeB        
      MMALIB_UINT8,             //dataTypeC        
      MMALIB_LINEAR,            //mode             
      0,                        //circularOffset
      64,                       //totalN
      64,                       //subN
      0,                        //validColsPerRowIn
      0,                        //validRowsIn
      0,                        //outputPitchPerRow
      0,                        //inputPitchPerRow
      8192,                     //validColsInlast
      0,                        //validColsPerRowInlast
      0,                        //validRowsInlast
      1,                        //numGroupsPerKernel
      MMALIB_TEST_OUTPUT_MSMC,  //outputDataLocation
      205,                      //testID
   },
#endif

#if ((TEST_CASE == 222) || (TEST_CATEGORY == 1000))
   {
      RANDOM,                   //testPattern
      NULL, NULL, NULL,        
      3,                        //kernelWidth
      5,                        //kernelHeight
      1,                        //strideWidth
      1,                        //strideHeight
      1,                        //dilationHeight
      1,                        //dilationWidth
      64,                       //inWidth
      1,                        //pad
      32,                       //maxHeight
      2048,                     //inChoffset
      900,                      //validColsIn
      482,                      //kDim
      1088,                     //pitchA
      32,                       //numOfOutputChKerBuf
      1600,                     //pitchC 
      32,                       //subMChannels     
      32,                       //numInChannels    
      32,                       //numOutChannels   
      12,                       //qShift           
      20,                       //biasB     
      MMALIB_SUCCESS, //expectedStatusCode            
      MMALIB_RELU,              //activationType   
      MMALIB_INT16,             //dataTypeA        
      MMALIB_INT16,             //dataTypeB        
      MMALIB_INT16,             //dataTypeC        
      MMALIB_SE_CIRCULAR,       //mode             
      0,                        //circularOffset
      32,                       //totalN
      32,                       //subN
      0,                        //validColsPerRowIn
      0,                        //validRowsIn
      0,                        //outputPitchPerRow
      0,                        //inputPitchPerRow
      900,                      //validColsInlast
      0,                        //validColsPerRowInlast
      0,                        //validRowsInlast
      1,                        //numGroupsPerKernel
      MMALIB_TEST_OUTPUT_MSMC,  //outputDataLocation
      222,                      //testID
   },
#endif

#if ((TEST_CASE == 227) || (TEST_CATEGORY == 1000))
   {
      STATIC,                   //testPattern
      staticRefIn_case227,     
      staticRefKernel_case227, 
      staticRefOutput_case227, 
      1,                        //kernelWidth
      1,                        //kernelHeight
      1,                        //strideWidth
      1,                        //strideHeight
      1,                        //dilationHeight
      1,                        //dilationWidth
      256,                      //inWidth
      0,                        //pad
      16,                       //maxHeight
      1088,                     //inChoffset
      512,                      //validColsIn
      320,                      //kDim
      576,                      //pitchA
      64,                       //numOfOutputChKerBuf
      1088,                     //pitchC 
      64,                       //subMChannels     
      256,                      //numInChannels    
      64,                       //numOutChannels   
      11,                       //qShift           
      20,                       //biasB     
      MMALIB_SUCCESS, //expectedStatusCode            
      MMALIB_RELU,              //activationType   
      MMALIB_INT8,              //dataTypeA        
      MMALIB_UINT8,             //dataTypeB        
      MMALIB_UINT8,             //dataTypeC        
      MMALIB_LINEAR,            //mode             
      0,                        //circularOffset
      64,                       //totalN
      64,                       //subN
      0,                        //validColsPerRowIn
      0,                        //validRowsIn
      0,                        //outputPitchPerRow
      0,                        //inputPitchPerRow
      512,                      //validColsInlast
      0,                        //validColsPerRowInlast
      0,                        //validRowsInlast
      1,                        //numGroupsPerKernel
      MMALIB_TEST_OUTPUT_MSMC,  //outputDataLocation
      227,                      //testID
   },
#endif

#if ((TEST_CASE == 237) || (TEST_CATEGORY == 1000))
   {
      RANDOM,                   //testPattern
      NULL, NULL, NULL,        
      1,                        //kernelWidth
      1,                        //kernelHeight
      1,                        //strideWidth
      1,                        //strideHeight
      1,                        //dilationHeight
      1,                        //dilationWidth
      32,                       //inWidth
      1,                        //pad
      16,                       //maxHeight
      576,                      //inChoffset
      256,                      //validColsIn
      513,                      //kDim
      576,                      //pitchA
      128,                      //numOfOutputChKerBuf
      576,                      //pitchC 
      128,                      //subMChannels     
      512,                      //numInChannels    
      256,                      //numOutChannels   
      9,                        //qShift           
      20,                       //biasB     
      MMALIB_SUCCESS, //expectedStatusCode            
      MMALIB_RELU,              //activationType   
      MMALIB_INT8,              //dataTypeA        
      MMALIB_UINT8,             //dataTypeB        
      MMALIB_UINT8,             //dataTypeC        
      MMALIB_LINEAR,            //mode             
      0,                        //circularOffset
      256,                      //totalN
      256,                      //subN
      0,                        //validColsPerRowIn
      0,                        //validRowsIn
      0,                        //outputPitchPerRow
      0,                        //inputPitchPerRow
      256,                      //validColsInlast
      0,                        //validColsPerRowInlast
      0,                        //validRowsInlast
      1,                        //numGroupsPerKernel
      MMALIB_TEST_OUTPUT_MSMC,  //outputDataLocation
      237,                      //testID
   },
#endif

#if ((TEST_CASE == 281) || (TEST_CATEGORY == 1000))
   {
      STATIC,                   //testPattern
      staticRefIn_case281,     
      staticRefKernel_case281, 
      staticRefOutput_case281, 
      3,                        //kernelWidth
      3,                        //kernelHeight
      2,                        //strideWidth
      2,                        //strideHeight
      1,                        //dilationHeight
      1,                        //dilationWidth
      512,                      //inWidth
      1,                        //pad
      130,                      //maxHeight
      74880,                    //inChoffset
      74880,                    //validColsIn
      64,                       //kDim
      64,                       //pitchA
      32,                       //numOfOutputChKerBuf
      16384,                    //pitchC 
      32,                       //subMChannels     
      3,                        //numInChannels    
      32,                       //numOutChannels   
      9,                        //qShift           
      20,                       //biasB     
      MMALIB_SUCCESS, //expectedStatusCode            
      MMALIB_RELU,              //activationType   
      MMALIB_INT8,              //dataTypeA        
      MMALIB_UINT8,             //dataTypeB        
      MMALIB_UINT8,             //dataTypeC        
      MMALIB_LINEAR,            //mode             
      0,                        //circularOffset
      64,                       //totalN
      64,                       //subN
      513,                      //validColsPerRowIn
      130,                      //validRowsIn
      256,                      //outputPitchPerRow
      576,                      //inputPitchPerRow
      74880,                    //validColsInlast
      513,                      //validColsPerRowInlast
      130,                      //validRowsInlast
      1,                        //numGroupsPerKernel
      MMALIB_TEST_OUTPUT_MSMC,  //outputDataLocation
      281,                      //testID
   },
#endif

// #if (defined(ALL_TEST_CASES) || (TEST_CATEGORY == 200) || (EXTENDED_TEST_CASE == 500))
// // added to test subMChannels < MMA_SIZE but have multiple batches
//    {
//       STATIC,                   //testPattern
//       staticRefIn_case500,     
//       staticRefKernel_case500, 
//       staticRefOutput_case500, 
//       3,                        //kernelWidth
//       3,                        //kernelHeight
//       3,                        //strideWidth
//       3,                        //strideHeight
//       1,                        //dilationHeight
//       1,                        //dilationWidth
//       256,                      //inWidth
//       1,                        //pad
//       32,                       //maxHeight
//       8192,                     //inChoffset
//       2240,                     //validColsIn
//       320,                      //kDim
//       320,                      //pitchA
//       64,                       //numOfOutputChKerBuf
//       264,                      //pitchC 
//       27,                       //subMChannels     
//       32,                       //numInChannels    
//       64,                       //numOutChannels   
//       10,                       //qShift           
//       1,                        //biasB     
//      MMALIB_SUCCESS, //expectedStatusCode            
//       MMALIB_RELU,              //activationType   
//       MMALIB_INT8,              //dataTypeA        
//       MMALIB_UINT8,             //dataTypeB        
//       MMALIB_UINT8,             //dataTypeC        
//       MMALIB_SE_CIRCULAR,       //mode             
//       0,                        //circularOffset
//       64,                       //totalN
//       64,                       //subN
//       257,                      //validColsPerRowIn
//       7,                        //validRowsIn
//       132,                      //outputPitchPerRow
//       320,                      //inputPitchPerRow
//       2240,                     //validColsInlast
//       257,                      //validColsPerRowInlast
//       7,                        //validRowsInlast
//       1,                        //numGroupsPerKernel
//       MMALIB_TEST_OUTPUT_MSMC,  //outputDataLocation
//       500,                      //testID
//    },
// #endif

};

void convolve_row_ixX_ixX_oxX_getTestParams (convolve_row_ixX_ixX_oxX_testParams_t * *params, int32_t *numTests)
{
   *params = testParams;
   *numTests = sizeof(testParams) / sizeof(convolve_row_ixX_ixX_oxX_testParams_t);
}


/* ======================================================================== */
/* End of file                                                              */
/* ------------------------------------------------------------------------ */
/* Copyright (c) 2016 Texas Instruments, Incorporated.                      */
/* All Rights Reserved.                                                     */
/* ======================================================================== */
