/******************************************************************************
 *                                                                             *
 * module name       :MMALIB                                                   *
 *                                                                             *
 * module descripton :Matrix Multiply Accelerator Library module for C7x+MMA   *
 *                                                                             *
 * Copyright (C) 2017-2018 Texas Instruments Incorporated - http://www.ti.com/ *
 * ALL RIGHTS RESERVED                                                         *
 *                                                                             *
 ******************************************************************************/

/*This file is autogenerated*/
/*Please do not edit*/


#include "MMALIB_CNN_convolve_col_smallNo_ixX_ixX_oxX_idat.h"

#define ALL_TEST_CASES

#if (defined(ALL_TEST_CASES) || (TEST_CATEGORY == 1000) || (TEST_CASE == 1001))
#include "test_data/MMALIB_CNN_convolve_col_smallNo_ixX_ixX_oxX_idat_testcase1001.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CATEGORY == 1000) || (TEST_CASE == 1002))
#include "test_data/MMALIB_CNN_convolve_col_smallNo_ixX_ixX_oxX_idat_testcase1002.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CATEGORY == 1000) || (TEST_CASE == 1003))
#include "test_data/MMALIB_CNN_convolve_col_smallNo_ixX_ixX_oxX_idat_testcase1003.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CATEGORY == 1000) || (TEST_CASE == 1004))
#include "test_data/MMALIB_CNN_convolve_col_smallNo_ixX_ixX_oxX_idat_testcase1004.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CATEGORY == 1000) || (TEST_CASE == 1005))
#include "test_data/MMALIB_CNN_convolve_col_smallNo_ixX_ixX_oxX_idat_testcase1005.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CATEGORY == 1000) || (TEST_CASE == 1006))
#include "test_data/MMALIB_CNN_convolve_col_smallNo_ixX_ixX_oxX_idat_testcase1006.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CATEGORY == 1000) || (TEST_CASE == 1007))
#include "test_data/MMALIB_CNN_convolve_col_smallNo_ixX_ixX_oxX_idat_testcase1007.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CATEGORY == 1000) || (TEST_CASE == 1008))
#include "test_data/MMALIB_CNN_convolve_col_smallNo_ixX_ixX_oxX_idat_testcase1008.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CATEGORY == 1000) || (TEST_CASE == 1009))
#include "test_data/MMALIB_CNN_convolve_col_smallNo_ixX_ixX_oxX_idat_testcase1009.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CATEGORY == 1000) || (TEST_CASE == 1010))
#include "test_data/MMALIB_CNN_convolve_col_smallNo_ixX_ixX_oxX_idat_testcase1010.h"
#endif


static MMALIB_CNN_convolve_col_smallNo_ixX_ixX_oxX_testParams_t testParams[] =
{

#if (defined(ALL_TEST_CASES) || (TEST_CATEGORY == 1000) || (TEST_CASE == 1001))
{
      STATIC,                  // testPattern
      staticRefKernel_test1001,// staticRefKernel_test
      NULL,                    // staticRefBias_test
      staticRefIn_test1001,    // staticRefIn_test
      NULL,                    // staticRefShift_test
      NULL,                    // staticRefBiasB_test
      staticRefOut_test1001,   // staticRefOut_test
      NULL,                    // dynamicRangeMin_test
      NULL,                    // dynamicRangeMax_test
      5,                       // kernelWidth
      5,                       // kernelHeight
      1,                       // strideX
      1,                       // strideY
      1,                       // dilationHeight
      1,                       // dilationWidth
      256,                     // Lc
      256,                     // Lr
      1,                       // numInChannels
      1,                       // numOutChannels
      1,                       // numGroupsPerKernel
      0,                       // qShift
      MMALIB_CONVOLVE_COL_SHIFT_SINGLE,// shiftMethod
      MMALIB_SUCCESS,          // expectedStatus
      1,                       // biasB
      1,                       // numBiasVals
      MMALIB_SATURATION,       // activationType
      MMALIB_INT8,             // dataTypeA
      MMALIB_INT8,             // dataTypeB
      MMALIB_INT8,             // dataTypeC
      MMALIB_TEST_OUTPUT_MSMC,  // outputDataLocation
      1,                        // repetitions
      1001,                    // testID
},
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CATEGORY == 1000) || (TEST_CASE == 1002))
{
      STATIC,                  // testPattern
      staticRefKernel_test1002,// staticRefKernel_test
      NULL,                    // staticRefBias_test
      staticRefIn_test1002,    // staticRefIn_test
      NULL,                    // staticRefShift_test
      NULL,                    // staticRefBiasB_test
      staticRefOut_test1002,   // staticRefOut_test
      NULL,                    // dynamicRangeMin_test
      NULL,                    // dynamicRangeMax_test
      7,                       // kernelWidth
      7,                       // kernelHeight
      1,                       // strideX
      1,                       // strideY
      1,                       // dilationHeight
      1,                       // dilationWidth
      256,                     // Lc
      256,                     // Lr
      1,                       // numInChannels
      1,                       // numOutChannels
      1,                       // numGroupsPerKernel
      4,                       // qShift
      MMALIB_CONVOLVE_COL_SHIFT_SINGLE,// shiftMethod
      MMALIB_SUCCESS,          // expectedStatus
      1,                       // biasB
      1,                       // numBiasVals
      MMALIB_SATURATION,       // activationType
      MMALIB_INT8,             // dataTypeA
      MMALIB_INT8,             // dataTypeB
      MMALIB_INT8,             // dataTypeC
      MMALIB_TEST_OUTPUT_MSMC,  // outputDataLocation
      1,                        // repetitions
      1002,                    // testID
},
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CATEGORY == 1000) || (TEST_CASE == 1003))
{
      STATIC,                  // testPattern
      staticRefKernel_test1003,// staticRefKernel_test
      NULL,                    // staticRefBias_test
      staticRefIn_test1003,    // staticRefIn_test
      NULL,                    // staticRefShift_test
      NULL,                    // staticRefBiasB_test
      staticRefOut_test1003,   // staticRefOut_test
      NULL,                    // dynamicRangeMin_test
      NULL,                    // dynamicRangeMax_test
      3,                       // kernelWidth
      3,                       // kernelHeight
      1,                       // strideX
      1,                       // strideY
      1,                       // dilationHeight
      1,                       // dilationWidth
      128,                     // Lc
      256,                     // Lr
      1,                       // numInChannels
      1,                       // numOutChannels
      1,                       // numGroupsPerKernel
      8,                       // qShift
      MMALIB_CONVOLVE_COL_SHIFT_SINGLE,// shiftMethod
      MMALIB_SUCCESS,          // expectedStatus
      1,                       // biasB
      1,                       // numBiasVals
      MMALIB_RELU,             // activationType
      MMALIB_INT16,            // dataTypeA
      MMALIB_INT16,            // dataTypeB
      MMALIB_INT16,            // dataTypeC
      MMALIB_TEST_OUTPUT_MSMC,  // outputDataLocation
      1,                        // repetitions
      1003,                    // testID
},
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CATEGORY == 1000) || (TEST_CASE == 1004))
{
      STATIC,                  // testPattern
      staticRefKernel_test1004,// staticRefKernel_test
      NULL,                    // staticRefBias_test
      staticRefIn_test1004,    // staticRefIn_test
      NULL,                    // staticRefShift_test
      NULL,                    // staticRefBiasB_test
      staticRefOut_test1004,   // staticRefOut_test
      NULL,                    // dynamicRangeMin_test
      NULL,                    // dynamicRangeMax_test
      3,                       // kernelWidth
      3,                       // kernelHeight
      2,                       // strideX
      2,                       // strideY
      1,                       // dilationHeight
      1,                       // dilationWidth
      384,                     // Lc
      384,                     // Lr
      1,                       // numInChannels
      1,                       // numOutChannels
      1,                       // numGroupsPerKernel
      4,                       // qShift
      MMALIB_CONVOLVE_COL_SHIFT_SINGLE,// shiftMethod
      MMALIB_SUCCESS,          // expectedStatus
      1,                       // biasB
      1,                       // numBiasVals
      MMALIB_RELU,             // activationType
      MMALIB_INT8,             // dataTypeA
      MMALIB_INT8,             // dataTypeB
      MMALIB_INT8,             // dataTypeC
      MMALIB_TEST_OUTPUT_MSMC,  // outputDataLocation
      1,                        // repetitions
      1004,                    // testID
},
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CATEGORY == 1000) || (TEST_CASE == 1005))
{
      STATIC,                  // testPattern
      staticRefKernel_test1005,// staticRefKernel_test
      NULL,                    // staticRefBias_test
      staticRefIn_test1005,    // staticRefIn_test
      NULL,                    // staticRefShift_test
      NULL,                    // staticRefBiasB_test
      staticRefOut_test1005,   // staticRefOut_test
      NULL,                    // dynamicRangeMin_test
      NULL,                    // dynamicRangeMax_test
      3,                       // kernelWidth
      3,                       // kernelHeight
      1,                       // strideX
      1,                       // strideY
      1,                       // dilationHeight
      1,                       // dilationWidth
      256,                     // Lc
      128,                     // Lr
      1,                       // numInChannels
      1,                       // numOutChannels
      2,                       // numGroupsPerKernel
      4,                       // qShift
      MMALIB_CONVOLVE_COL_SHIFT_SINGLE,// shiftMethod
      MMALIB_SUCCESS,          // expectedStatus
      1,                       // biasB
      1,                       // numBiasVals
      MMALIB_RELU,             // activationType
      MMALIB_INT8,             // dataTypeA
      MMALIB_INT8,             // dataTypeB
      MMALIB_INT8,             // dataTypeC
      MMALIB_TEST_OUTPUT_MSMC,  // outputDataLocation
      1,                        // repetitions
      1005,                    // testID
},
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CATEGORY == 1000) || (TEST_CASE == 1006))
{
      STATIC,                  // testPattern
      staticRefKernel_test1006,// staticRefKernel_test
      NULL,                    // staticRefBias_test
      staticRefIn_test1006,    // staticRefIn_test
      NULL,                    // staticRefShift_test
      NULL,                    // staticRefBiasB_test
      staticRefOut_test1006,   // staticRefOut_test
      NULL,                    // dynamicRangeMin_test
      NULL,                    // dynamicRangeMax_test
      3,                       // kernelWidth
      3,                       // kernelHeight
      1,                       // strideX
      1,                       // strideY
      1,                       // dilationHeight
      1,                       // dilationWidth
      128,                     // Lc
      256,                     // Lr
      2,                       // numInChannels
      2,                       // numOutChannels
      1,                       // numGroupsPerKernel
      4,                       // qShift
      MMALIB_CONVOLVE_COL_SHIFT_SINGLE,// shiftMethod
      MMALIB_SUCCESS,          // expectedStatus
      1,                       // biasB
      1,                       // numBiasVals
      MMALIB_RELU,             // activationType
      MMALIB_INT8,             // dataTypeA
      MMALIB_INT8,             // dataTypeB
      MMALIB_INT8,             // dataTypeC
      MMALIB_TEST_OUTPUT_MSMC,  // outputDataLocation
      1,                        // repetitions
      1006,                    // testID
},
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CATEGORY == 1000) || (TEST_CASE == 1007))
{
      STATIC,                  // testPattern
      staticRefKernel_test1007,// staticRefKernel_test
      NULL,                    // staticRefBias_test
      staticRefIn_test1007,    // staticRefIn_test
      NULL,                    // staticRefShift_test
      NULL,                    // staticRefBiasB_test
      staticRefOut_test1007,   // staticRefOut_test
      NULL,                    // dynamicRangeMin_test
      NULL,                    // dynamicRangeMax_test
      3,                       // kernelWidth
      3,                       // kernelHeight
      1,                       // strideX
      1,                       // strideY
      1,                       // dilationHeight
      1,                       // dilationWidth
      64,                      // Lc
      1024,                    // Lr
      1,                       // numInChannels
      1,                       // numOutChannels
      1,                       // numGroupsPerKernel
      4,                       // qShift
      MMALIB_CONVOLVE_COL_SHIFT_SINGLE,// shiftMethod
      MMALIB_SUCCESS,          // expectedStatus
      1,                       // biasB
      1,                       // numBiasVals
      MMALIB_SATURATION,       // activationType
      MMALIB_INT8,             // dataTypeA
      MMALIB_INT8,             // dataTypeB
      MMALIB_INT8,             // dataTypeC
      MMALIB_TEST_OUTPUT_MSMC,  // outputDataLocation
      1,                        // repetitions
      1007,                    // testID
},
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CATEGORY == 1000) || (TEST_CASE == 1008))
{
      STATIC,                  // testPattern
      staticRefKernel_test1008,// staticRefKernel_test
      NULL,                    // staticRefBias_test
      staticRefIn_test1008,    // staticRefIn_test
      NULL,                    // staticRefShift_test
      NULL,                    // staticRefBiasB_test
      staticRefOut_test1008,   // staticRefOut_test
      NULL,                    // dynamicRangeMin_test
      NULL,                    // dynamicRangeMax_test
      3,                       // kernelWidth
      3,                       // kernelHeight
      1,                       // strideX
      1,                       // strideY
      1,                       // dilationHeight
      1,                       // dilationWidth
      64,                      // Lc
      128,                     // Lr
      1,                       // numInChannels
      1,                       // numOutChannels
      4,                       // numGroupsPerKernel
      4,                       // qShift
      MMALIB_CONVOLVE_COL_SHIFT_SINGLE,// shiftMethod
      MMALIB_SUCCESS,          // expectedStatus
      1,                       // biasB
      1,                       // numBiasVals
      MMALIB_SATURATION,       // activationType
      MMALIB_INT8,             // dataTypeA
      MMALIB_INT8,             // dataTypeB
      MMALIB_INT8,             // dataTypeC
      MMALIB_TEST_OUTPUT_MSMC,  // outputDataLocation
      1,                        // repetitions
      1008,                    // testID
},
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CATEGORY == 1000) || (TEST_CASE == 1009))
{
      STATIC,                  // testPattern
      staticRefKernel_test1009,// staticRefKernel_test
      NULL,                    // staticRefBias_test
      staticRefIn_test1009,    // staticRefIn_test
      NULL,                    // staticRefShift_test
      NULL,                    // staticRefBiasB_test
      staticRefOut_test1009,   // staticRefOut_test
      NULL,                    // dynamicRangeMin_test
      NULL,                    // dynamicRangeMax_test
      3,                       // kernelWidth
      3,                       // kernelHeight
      1,                       // strideX
      1,                       // strideY
      1,                       // dilationHeight
      1,                       // dilationWidth
      128,                     // Lc
      64,                      // Lr
      2,                       // numInChannels
      2,                       // numOutChannels
      4,                       // numGroupsPerKernel
      4,                       // qShift
      MMALIB_CONVOLVE_COL_SHIFT_SINGLE,// shiftMethod
      MMALIB_SUCCESS,          // expectedStatus
      1,                       // biasB
      1,                       // numBiasVals
      MMALIB_SATURATION,       // activationType
      MMALIB_INT8,             // dataTypeA
      MMALIB_INT8,             // dataTypeB
      MMALIB_INT8,             // dataTypeC
      MMALIB_TEST_OUTPUT_MSMC,  // outputDataLocation
      1,                        // repetitions
      1009,                    // testID
},
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CATEGORY == 1000) || (TEST_CASE == 1010))
{
      STATIC,                  // testPattern
      staticRefKernel_test1010,// staticRefKernel_test
      NULL,                    // staticRefBias_test
      staticRefIn_test1010,    // staticRefIn_test
      NULL,                    // staticRefShift_test
      NULL,                    // staticRefBiasB_test
      staticRefOut_test1010,   // staticRefOut_test
      NULL,                    // dynamicRangeMin_test
      NULL,                    // dynamicRangeMax_test
      3,                       // kernelWidth
      3,                       // kernelHeight
      2,                       // strideX
      2,                       // strideY
      1,                       // dilationHeight
      1,                       // dilationWidth
      128,                     // Lc
      128,                     // Lr
      4,                       // numInChannels
      4,                       // numOutChannels
      2,                       // numGroupsPerKernel
      4,                       // qShift
      MMALIB_CONVOLVE_COL_SHIFT_SINGLE,// shiftMethod
      MMALIB_SUCCESS,          // expectedStatus
      1,                       // biasB
      1,                       // numBiasVals
      MMALIB_SATURATION,       // activationType
      MMALIB_INT8,             // dataTypeA
      MMALIB_INT8,             // dataTypeB
      MMALIB_INT8,             // dataTypeC
      MMALIB_TEST_OUTPUT_MSMC,  // outputDataLocation
      1,                        // repetitions
      1010,                    // testID
},
#endif

};  // do not delete this brace!

/* Sends the test parameter structure and number of tests */
void MMALIB_CNN_convolve_col_smallNo_ixX_ixX_oxX_getTestParams(MMALIB_CNN_convolve_col_smallNo_ixX_ixX_oxX_testParams_t **params, int32_t *numTests)
{
   *params   = testParams;
   *numTests = sizeof(testParams) / sizeof(MMALIB_CNN_convolve_col_smallNo_ixX_ixX_oxX_testParams_t);
}

/* ========================================================================== */
/*                           End of file                                      */
/* -------------------------------------------------------------------------- */
/*             Copyright (c) 2016 Texas Instruments, Incorporated.            */
/*                            All Rights Reserved.                            */
/* ========================================================================== */
